parameters:
#    guest_book.example.class: My\GuestBookBundle\Example

services:
#    guest_book.example:
#        class: %guest_book.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
